### ISSUE TITLE
How can we generate token while logging in user?

### ISSUE THREAD

**Issue by muhammadshakeel** [damirka/yii2-jwt#4]
Can you add a sample login action in documentation to help how we can generate token for authentication which can later on be validated through this?

**Comment by damirka** [comment]
Hi @muhammadshakeel. JWT is used in APIs to check income requests for valid signature. 
How do you want to use it?

**Comment by muhammadshakeel** [comment]
We need to use it for our api which will be used from our mobile app. Users
will login in response we assume to generate a jwt token for each user and
then every other request will contain this token to identify a valid user.

Am I wrong with Jwt?

**Comment by damirka** [comment]
You are right. Just had to be sure.
So what is unclear about it? There is no common way of doing it so I can only suggest you to make an `/auth` action for example and return token in JSON (or whatever) response.

```
<?php

class AuthController extends APIController
{
    public function actionAuth()
    {
        // some user identifying logic in here
        // ... 
        return ['token' => $user->getJWT()];
    }

    // other actions or methods 
    // ...
}
```

**Comment by muhammadshakeel** [comment]
Thanks alot @damirka things are very much clear now.
