### ISSUE TITLE
How to add custom payload (f.eks. "name", or "isAdmin") in token?

### ISSUE THREAD

**Issue by dakipro** [damirka/yii2-jwt#8]
Hi,
I didn't find any method that would do this, do you have a suggestion on how to add custom elements in json array, as a payload?
Something like default example from https://jwt.io/
PAYLOAD:DATA

{
  "sub": "1234567890",
  **"name": "John Doe",
  "admin": true**
}

Thanks

**Comment by damirka** [comment]
Hello @dakipro. Custom payload data is not supported in this extension. 
But I've found a [fork](https://github.com/Yemsheng/yii2-jwt) for you which does. You'd better use this one.

**Comment by dakipro** [comment]
Thanks. I could not find custom payload on that one either, for now I will keep it as is, and extend it later if needed.

**Comment by damirka** [comment]
Sure. Be free to send a PR. :+1:
